import type { TerrainMap, TerrainTileset } from "../../three/assets.ts";

export const sampleTileset = {
  type: "tileset",
  name: "Test",
  image: "tileset.png",
  tilewidth: 128,
  tileheight: 96,
  tilecount: 4,
  rows: 2,
  columns: 2,
  spacing: 0,
  margin: 0,
  imagewidth: 256,
  imageheight: 192,
  tiles: [
    { id: 0, probability: 1, properties: [{ name: "NESW", type: "string", value: "0000" }, { name: "CENTER", type: "float", value: 0 }] },
    { id: 1, probability: 1, properties: [{ name: "NESW", type: "string", value: "0100" }, { name: "CENTER", type: "float", value: 0 }] },
    { id: 2, probability: 1, properties: [{ name: "NESW", type: "string", value: "1000" }, { name: "CENTER", type: "float", value: 0 }] },
    { id: 3, probability: 1, properties: [{ name: "NESW", type: "string", value: "1100" }, { name: "CENTER", type: "float", value: 0.5 }] },
  ],
  version: "1.10",
  tiledversion: "1.11.2",
  properties: [{ name: "elevationYOffsetPx", type: "int", value: 16 }],
} satisfies TerrainTileset;

export const sampleMap = {
  type: "map",
  orientation: "isometric",
  renderorder: "right-down",
  width: 3,
  height: 3,
  tilewidth: 128,
  tileheight: 64,
  layers: [
    {
      id: 1,
      name: "level-0",
      opacity: 1,
      type: "tilelayer",
      visible: true,
      x: 0,
      y: 0,
      offsetx: 0,
      offsety: 0,
      height: 3,
      width: 3,
      data: [1, 2, 1, 1, 4, 1, 1, 1, 3],
      properties: [{ name: "level", type: "int", value: 0 }],
    },
    {
      id: 2,
      name: "level-1",
      opacity: 1,
      type: "tilelayer",
      visible: true,
      x: 0,
      y: 0,
      offsetx: 0,
      offsety: -16,
      height: 3,
      width: 3,
      data: [0, 0, 0, 0, 2, 0, 0, 0, 0],
      properties: [{ name: "level", type: "int", value: 1 }],
    },
  ],
  tilesets: [{ firstgid: 1, ...sampleTileset }],
} satisfies TerrainMap;
