export const TILE_HEIGHT_PX = 16;
export const SMALL_WORLD_FACTOR = 12;
export const PIXELS_PER_METER = 12; // Pixels per meter
export const ENEMY_SPRITE = "enemy"; // Enemy sprite key
export const CANNON_SPRITE = "cannon"; // Cannon sprite key
export const BULLET_SPRITE = "bullet"; // Bullet sprite key
export const CANNON_SHADOW_SPRITE = "cannon-shadow";
export const BULLET_SHADOW_SPRITE = "bullet-shadow";
export const PARTICLE_SPRITE = "particle";
export const PIXEL_CANNON_SPRITE = "pixel-cannon";
export const CANNON_WHEELS_SPRITE = "cannon-wheels";
export const CANNON_WHEELS_SPRITE_ROTATION = Math.PI * 1.5; // to make it face right
export const FLARES = "flares";
export const PLAY_SOUNDS = true;
export const VISIBLE_UPDATE_INTERVAL = 1; // Target 60 FPS when visible
export const INVISIBLE_UPDATE_INTERVAL = 1000 / 10; // Target 10 FPS when invisible
